const ShopActionTypes ={
    FETECH_COLLECTIONS_START:'FETECH_COLLECTIONS_START',
    FETECH_COLLECTIONS_SUCCESS:'FETECH_COLLECTIONS_SUCCESS',
    FETECH_COLLECTIONS_FAILURE:'FETECH_COLLECTIONS_SUCCESS'
};



export default ShopActionTypes;